version: '3.3'
services:
  backend:
    build: .
    ports:
      - "80:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rent
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "54322:5432"