version: '3.3'
services:
  backend:
    build: .
    ports:
      - "80:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rent
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "54322:5432"
        
  minio:
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: testkey
      MINIO_ROOT_PASSWORD: testsecret
    volumes:
      - ./minio:/data
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"